### ISSUE TITLE
android permission.

### ISSUE THREAD

**Issue by TheMagicianThing** [Pittvandewitt/Wavelet#183]
When I try to do the grant android dump permission I get 
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
        at android.app.ContextImpl.enforce(ContextImpl.java:2028)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2056)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1445)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1426)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2300)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:251)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22149)
        at android.os.Binder.shellCommand(Binder.java:929)
        at android.os.Binder.onTransact(Binder.java:813)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4687)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4399)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)

I'm on a xiaomi redmi note 9 pro, running MIUI 12.5.11 and I've tried the beta.

**Comment by Pittvandewitt** [comment]
Quoting the documentation: On Xiaomi devices, it is mandatory to enable USB debugging (Security Settings)

**Comment by TheMagicianThing** [comment]
> Quoting the documentation: On Xiaomi devices, it is mandatory to enable USB debugging (Security Settings)

You really think I didn't enable it before trying anything adb related? it was on when I tried it
