### ISSUE TITLE
pm grant issue

### ISSUE THREAD

**Issue by passive-Gravity** [Pittvandewitt/Wavelet#189]
I keep getting this issue 
`Nord:/ $ pm grant com.pittvandewitt.wavelet android.permission.DUMP

Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
        at android.app.ContextImpl.enforce(ContextImpl.java:2186)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2214)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1470)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1452)
        at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:378)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2419)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:260)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25898)
        at android.os.Binder.shellCommand(Binder.java:970)
        at android.os.Binder.onTransact(Binder.java:854)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8982)
        at android.os.Binder.execTransactInternal(Binder.java:1226)
        at android.os.Binder.execTransact(Binder.java:1163)`
I am using **Nord OxygenOS 12.1**

**Comment by Pittvandewitt** [comment]
The suggestions here will probably guide you in the right direction: https://www.reddit.com/r/OnePlus9Pro/comments/tey51z/adb_permission_issues/
Please let me know what worked so I can update the instructions.

**Comment by passive-Gravity** [comment]
> The suggestions here will probably guide you in the right direction: https://www.reddit.com/r/OnePlus9Pro/comments/tey51z/adb_permission_issues/ Please let me know what worked so I can update the instructions.

Thank you for this, it worked. I had hard time finding the _disable permission monitoring_ . But after enabling that and rebooting the phone it wored.
