### ISSUE TITLE
I cant give Wavelet DUMP permission

### ISSUE THREAD

**Issue by daniiielllll** [Pittvandewitt/Wavelet#230]
I cant give Wavelet DUMP permission even tho i have done everthing it says+i have the newest version and the debugging(security) 
I have a Xiaomi Poco F3 and this is what the shell says

alioth:/ $ pm grant com.pittvandewitt.wavelet android.permission.DUMP                                

Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
        at android.app.ContextImpl.enforce(ContextImpl.java:2189)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2217)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1463)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1445)
        at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:378)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2384)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:260)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:24996)
        at android.os.Binder.shellCommand(Binder.java:953)
        at android.os.Binder.onTransact(Binder.java:837)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8601)
        at android.os.Binder.execTransactInternal(Binder.java:1187)
        at android.os.Binder.execTransact(Binder.java:1146)

**Comment by Pittvandewitt** [comment]
Try enabling "USB debugging (Security settings)" in your device developer settings before granting the DUMP permission.

**Comment by iz0eyj** [comment]
Same problem on Poco F4 GT (always Xiaomi, Android 14, HyperOS), USB Debug is Okay.
It seems it's impossibile to change permission for User 2000.
Great on OnePlus 6T, great on Lenovo Yoga Tab 13, working in progress on Lenovo Duet (ChromeOS), impossibile to grant permissions on Poco F4 GT.
Maybe it depends on Android 14 and/or HyperOS?  Are there solutions?
